# Generated by Django 3.0 on 2020-04-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeNumber', models.CharField(max_length=10, verbose_name='学院编号')),
                ('name', models.CharField(max_length=200, verbose_name='学院名称')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.CharField(max_length=20, verbose_name='课程ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='毕业要求编号')),
                ('content', models.CharField(max_length=1000, null=True, verbose_name='毕业要求内容')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationReqPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='指标点编号')),
                ('content', models.CharField(max_length=1000, null=True, verbose_name='指标点内容')),
                ('GraduationReq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.GraduationReq')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorNumber', models.CharField(max_length=20, verbose_name='专业编号')),
                ('name', models.CharField(max_length=200, verbose_name='专业名称')),
            ],
        ),
        migrations.CreateModel(
            name='MajorClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classNumber', models.CharField(max_length=20, verbose_name='班级编号')),
                ('name', models.CharField(max_length=200, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('number', models.CharField(max_length=20, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majorPerson.Person')),
                ('grade', models.CharField(max_length=5, null=True, verbose_name='年级')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.College')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Major')),
            ],
            bases=('majorPerson.person',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='用户类别')),
                ('password', models.CharField(default='12345678', max_length=64, verbose_name='密码')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SupportMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='权重')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Course')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.GraduationReqPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Course')),
                ('majorClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.MajorClass')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='majorPerson.Person')),
                ('reachingDegree', models.FloatField(null=True, verbose_name='最终达成度')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.College')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Staff')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Major')),
                ('majorClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.MajorClass')),
            ],
            bases=('majorPerson.person',),
        ),
        migrations.CreateModel(
            name='PointMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(null=True, verbose_name='达成度')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.GraduationReqPoint')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Student')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationReqMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(null=True, verbose_name='达成度')),
                ('GraduationReq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.GraduationReq')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField(null=True, verbose_name='评价值')),
                ('status', models.IntegerField(default=0, verbose_name='审核状态')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Course')),
                ('point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.GraduationReqPoint')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='coursePerson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Staff'),
        ),
    ]
