# Generated by Django 3.0 on 2020-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorPerson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='grade',
        ),
        migrations.AddField(
            model_name='person',
            name='grade',
            field=models.CharField(max_length=5, null=True, verbose_name='年级'),
        ),
    ]
