# Generated by Django 3.0 on 2020-04-23 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('majorPerson', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='coursemark',
        #     name='status',
        # ),
        # migrations.RemoveField(
        #     model_name='staff',
        #     name='grade',
        # ),
        # migrations.AddField(
        #     model_name='majorclass',
        #     name='grade',
        #     field=models.CharField(max_length=5, null=True, verbose_name='年级'),
        # ),
        # migrations.AddField(
        #     model_name='majorclass',
        #     name='major',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Major'),
        # ),
        # migrations.AddField(
        #     model_name='person',
        #     name='grade',
        #     field=models.CharField(max_length=5, null=True, verbose_name='年级'),
        # ),
        # migrations.AddField(
        #     model_name='teach',
        #     name='status',
        #     field=models.IntegerField(default=0, verbose_name='审核状态'),
        # ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500, null=True, verbose_name='驳回原因')),
                ('examine_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='审核日期')),
                ('status', models.BooleanField(default=False, verbose_name='是否处理')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Course')),
                ('coursePerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursePerson', to='majorPerson.Staff')),
                ('majorClass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.MajorClass')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Staff')),
            ],
        ),
    ]
