# Generated by Django 3.0 on 2020-04-20 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majorPerson', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='coursemark',
        #     name='status',
        # ),
        # migrations.RemoveField(
        #     model_name='staff',
        #     name='grade',
        # ),
        migrations.AddField(
            model_name='majorclass',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Major'),
        ),
        # migrations.AddField(
        #     model_name='person',
        #     name='grade',
        #     field=models.CharField(max_length=5, null=True, verbose_name='年级'),
        # ),
        # migrations.AddField(
        #     model_name='teach',
        #     name='status',
        #     field=models.IntegerField(default=0, verbose_name='审核状态'),
        # ),
    ]
