# Generated by Django 3.0 on 2020-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorPerson', '0002_auto_20200419_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemark',
            name='status',
        ),
        migrations.AddField(
            model_name='teach',
            name='status',
            field=models.IntegerField(default=0, verbose_name='审核状态'),
        ),
    ]
