# Generated by Django 3.0 on 2020-04-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majorPerson', '0003_auto_20200419_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorclass',
            name='grade',
            field=models.CharField(max_length=5, null=True, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='majorclass',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorPerson.Major'),
        ),
    ]
